linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bidichk
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gofmt
    - gosec
    - nakedret
    - nilerr
    - nilnil
    - perfsprint
    - prealloc
    - makezero
    - protogetter
    - reassign
    - rowserrcheck
    - tagliatelle
    - bodyclose
    - zerologlint
    - errname
    - unconvert
    - usestdlibvars
    - revive
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  nakedret:
    max-func-lines: 1
  gosec:
    excludes:
      - G102
      - G114
  nilnil:
    checked-types:
      - func
      - iface
      - map
      - chan
  revive:
    enable-all-rules: false
    rules:
      - name: time-naming
        disabled: false
      - name: errorf
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: if-return
        disabled: false
      - name: range
        disabled: false
      - name: confusing-naming
        disabled: false
      - name: modifies-parameter
        disabled: false
      - name: deep-exit
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: unnecessary-stmt
        disabled: false
      - name: struct-tag
        disabled: false
      - name: modifies-value-receiver
        disabled: false
      - name: waitgroup-by-value
        disabled: false
      - name: atomic
        disabled: false
      - name: defer
        disabled: false
      - name: use-any
        disabled: false
      - name: datarace
        disabled: false
