linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bidichk
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gofmt
    - gosec
    - nakedret
    - nilerr
    - nilnil
    - perfsprint
    - prealloc
    - makezero
    - protogetter
    - reassign
    - rowserrcheck
    - tagliatelle
    - bodyclose
    - zerologlint
    - errname
    - unconvert
    - usestdlibvars
    - revive
    - protogetter
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  nakedret:
    max-func-lines: 1
  gosec:
    excludes:
      - G102
      - G114
  nilnil:
    checked-types:
      - func
      - iface
      - map
      - chan
  revive:
    enable-all-rules: true
    rules:
      - name: var-naming
        disabled: true
      - name: empty-lines
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: add-constant
        disabled: true
run:
  skip-dirs:
    - bin
    - tools
