// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package models

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// NewTodo defines model for NewTodo.
type NewTodo struct {
	Title string `json:"title"`
}

// Todo defines model for Todo.
type Todo struct {
	Completed bool               `json:"completed"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
}

// Id defines model for id.
type Id = int

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = NewTodo
