name: Blaze lint and build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4

      - name: Build the application
        run: make build
