name: Mirror Repository

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Target Repository
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
          TARGET_REPO_URL: github.com/quinck-io/blaze
        run: |
          TARGET=https://$TARGET_REPO_PAT@$TARGET_REPO_URL
          git remote add target $TARGET
          git push --mirror $TARGET
